<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [8]:
import pandas as pd
import glob
import numpy as np

STOCK_DF_PATH = 'stock_df'

In [16]:
# Read core data into memory from the scraped csv files
all_files = glob.glob(STOCK_DF_PATH + "/Individual_Companies/*.csv")

csv_li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    df = df.drop(columns=['Unnamed: 0'])
    share_ticker = str(filename[30:filename.find('_',30)])
    # Make ticker and date index
    ticker_index = pd.Index( np.array([share_ticker]*len(df)), name='ticker')
    date_index = pd.Index(np.array(df['date']),name='date')
    df = df.set_index([date_index, ticker_index], append=True) 
    df = df.drop(columns=['date'])
    # Calculate daily growths
    df['growth']=df.adjClose.pct_change() # gets growth rates
    df['log_ret'] = np.log(df.adjClose) - np.log(df.adjClose.shift(1)) # use log returns
    # Drop first four dates from DataFrame - this is done so data can be split into equal batches
    df = df.iloc[4:,:]
    csv_li.append(df)
    
csv_li    
all_share_df = pd.concat(csv_li, axis=0, ignore_index=False)

display(all_share_df)

,,,close,high,low,open,volume,adjClose,adjHigh,adjLow,adjOpen,adjVolume,divCash,splitFactor,marketCap,enterpriseVal,peRatio,pbRatio,trailingPEG1Y,growth,log_ret
,date,ticker,,,,,,,,,,,,,,,,,,,
4,2017-05-10 00:00:00+00:00,DIS,109.66,109.660,108.13,109.00,17045219,104.990936,104.990936,103.526080,104.359037,17045219,0.0,1.0,1.642981e+11,1.821511e+11,19.005199,3.668515,1.244841,-0.021504,-0.021739
5,2017-05-11 00:00:00+00:00,DIS,109.58,110.005,108.50,109.74,7938863,104.914342,105.321247,103.880326,105.067530,7938863,0.0,1.0,1.641783e+11,1.820313e+11,18.991334,3.665838,1.243932,-0.000730,-0.000730
6,2017-05-12 00:00:00+00:00,DIS,109.69,109.890,109.27,109.80,4967734,105.019659,105.211143,104.617541,105.124975,4967734,0.0,1.0,1.643431e+11,1.821961e+11,19.010399,3.669518,1.245181,0.001004,0.001003
7,2017-05-15 00:00:00+00:00,DIS,109.13,110.080,109.12,109.73,5913123,104.483502,105.393053,104.473928,105.057955,5913123,0.0,1.0,1.635040e+11,1.813570e+11,18.913345,3.650784,1.238824,-0.005105,-0.005118
8,2017-05-16 00:00:00+00:00,DIS,107.98,109.230,107.82,109.12,10016682,103.382466,104.579244,103.229279,104.473928,10016682,0.0,1.0,1.617811e+11,1.796341e+11,18.714038,3.612313,1.225769,-0.010538,-0.010594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749,2020-04-27 00:00:00+00:00,HP,17.72,17.850,16.57,17.15,3161311,17.720000,17.850000,16.570000,17.150000,3161311,0.0,1.0,1.929312e+09,2.053657e+09,-77.043478,0.483375,-1.309739,-0.002814,-0.002818
750,2020-04-28 00:00:00+00:00,HP,18.98,19.100,17.81,18.77,2981551,18.980000,19.100000,17.810000,18.770000,2981551,0.0,1.0,2.066498e+09,2.190843e+09,-82.521739,0.517745,-1.402870,0.071106,0.068692
751,2020-04-29 00:00:00+00:00,HP,21.22,21.280,19.50,20.09,5419604,21.220000,21.280000,19.500000,20.090000,5419604,0.0,1.0,2.310384e+09,2.434729e+09,-92.260870,0.578849,-1.568435,0.118019,0.111558
752,2020-04-30 00:00:00+00:00,HP,19.77,21.600,19.42,21.54,17540759,19.770000,21.600000,19.420000,21.540000,17540759,0.0,1.0,2.152511e+09,2.276856e+09,-85.956522,0.539295,-1.461261,-0.068332,-0.070778
753,2020-05-01 00:00:00+00:00,HP,16.81,19.660,16.66,18.00,6089513,16.810000,19.660000,16.660000,18.000000,6089513,0.0,1.0,1.830233e+09,1.954578e+09,-73.086957,0.458551,-1.242478,-0.149722,-0.162192

In [17]:
# Create df of each share price per day 
sp_per_day = all_share_df.reset_index().set_index('date').pivot(columns='ticker', values='adjClose')

# Find shares with missing data as a result of company restructuring and remove from dataframe
null_columns=sp_per_day.columns[sp_per_day.isnull().any()]
sp_per_day = sp_per_day.drop(columns=null_columns)

# Remove these restructured companies from all_share_df
all_share_df = all_share_df.reset_index().set_index('date').drop(columns=['level_0'])
all_share_df=all_share_df[~all_share_df['ticker'].isin(null_columns)]

display(sp_per_day.head(2))

all_share_df.to_csv(STOCK_DF_PATH + '/all_share_sp.csv')
sp_per_day.to_csv(STOCK_DF_PATH + '/sp_per_day.csv')

ticker,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS
date,,,,,,,,,,,,,,,,,,,,,
2017-05-10 00:00:00+00:00,54.787429,45.807789,145.012956,146.665034,57.552632,83.507863,131.80,42.200128,115.432468,136.15,...,41.060180,61.279818,72.588375,61.159223,25.467061,49.212892,65.771839,116.626205,38.439347,58.799686
2017-05-11 00:00:00+00:00,54.748483,45.071765,144.804604,147.928233,56.959486,84.190023,130.85,41.593205,115.051503,136.29,...,41.297998,61.241886,73.208713,61.335305,25.395323,49.058620,66.010558,118.119535,37.932331,58.622992

In [11]:
# Create a table where with market caps for all shares added (giving the S&P 500 index)
sp_df = all_share_df.groupby(level=0).sum()
display(sp_df.tail())
sp_df.to_csv(STOCK_DF_PATH + '/aggregated_sp.csv')
# Note: only market cap is calculated correctly in this table (can't just sum other values)

,close,high,low,open,volume,adjClose,adjHigh,adjLow,adjOpen,adjVolume,divCash,splitFactor,marketCap,enterpriseVal,peRatio,pbRatio,trailingPEG1Y,growth,log_ret
date,,,,,,,,,,,,,,,,,,,
2020-04-27 00:00:00+00:00,54912.365,55515.6021,53727.9939,54323.9908,2746618518,54904.733353,55507.897758,53720.559656,54316.491568,2746618518,0.5600,479.0,2.463450e+13,3.048946e+13,9256.185782,2712.646431,87.503042,13.701367,13.316118
2020-04-28 00:00:00+00:00,54873.200,56511.4278,54267.0209,55821.1513,3205370070,54865.877471,56503.904948,54259.762236,55813.725981,3205370070,0.3900,479.0,2.449203e+13,3.034699e+13,9185.296296,2722.106268,87.643423,6.740806,6.420954
2020-04-29 00:00:00+00:00,56244.660,57182.9266,55029.8576,55989.4377,3837002520,56239.084685,57177.241034,55024.387853,55983.850498,3837002520,1.8575,479.0,2.511771e+13,3.097267e+13,9428.928656,2725.740394,86.654894,15.821701,15.158120
2020-04-30 00:00:00+00:00,55414.175,56500.2850,54585.7996,55702.5144,3669322514,55411.386067,56497.436738,54583.045803,55699.684234,3669322514,2.6763,479.0,2.489559e+13,3.075055e+13,9340.052940,2709.381438,87.439957,-11.542333,-11.864532
2020-05-01 00:00:00+00:00,53807.180,54992.4509,53113.9635,54375.9335,2881525092,53807.180000,54992.450900,53113.963500,54375.933500,2881525092,2.6750,479.0,2.418428e+13,3.003924e+13,9040.471066,2664.131562,88.544699,-17.229180,-17.757860